version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
